# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'conver.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_A_Simple_Convertor(object):
    def setupUi(self, A_Simple_Convertor):
        A_Simple_Convertor.setObjectName("A_Simple_Convertor")
        A_Simple_Convertor.resize(342, 279)
        self.centralwidget = QtWidgets.QWidget(A_Simple_Convertor)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 120, 41, 25))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(180, 120, 21, 25))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 190, 104, 35))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 190, 104, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 120, 113, 33))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 120, 113, 33))
        self.lineEdit_2.setObjectName("lineEdit_2")
        A_Simple_Convertor.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(A_Simple_Convertor)
        self.statusbar.setObjectName("statusbar")
        A_Simple_Convertor.setStatusBar(self.statusbar)

        self.retranslateUi(A_Simple_Convertor)
        QtCore.QMetaObject.connectSlotsByName(A_Simple_Convertor)

    def retranslateUi(self, A_Simple_Convertor):
        _translate = QtCore.QCoreApplication.translate
        A_Simple_Convertor.setWindowTitle(_translate("A_Simple_Convertor", "MainWindow"))
        self.label.setText(_translate("A_Simple_Convertor", "A Simple Convertor"))
        self.label_2.setText(_translate("A_Simple_Convertor", "From"))
        self.label_3.setText(_translate("A_Simple_Convertor", "TO"))
        self.pushButton.setText(_translate("A_Simple_Convertor", "Start"))
        self.pushButton_2.setText(_translate("A_Simple_Convertor", "Exit"))
