# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mywindow(object):
    def setupUi(self, mywindow):
        mywindow.setObjectName("mywindow")
        mywindow.resize(507, 346)
        self.centralwidget = QtWidgets.QWidget(mywindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 40, 281, 21))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(90, 180, 121, 35))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(250, 180, 161, 35))
        self.pushButton_2.setObjectName("pushButton_2")
        mywindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mywindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 507, 30))
        self.menubar.setObjectName("menubar")
        mywindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mywindow)
        self.statusbar.setObjectName("statusbar")
        mywindow.setStatusBar(self.statusbar)
        self.action112 = QtWidgets.QAction(mywindow)
        self.action112.setObjectName("action112")
        self.action113 = QtWidgets.QAction(mywindow)
        self.action113.setObjectName("action113")
        self.action114 = QtWidgets.QAction(mywindow)
        self.action114.setObjectName("action114")

        self.retranslateUi(mywindow)
        QtCore.QMetaObject.connectSlotsByName(mywindow)

    def retranslateUi(self, mywindow):
        _translate = QtCore.QCoreApplication.translate
        mywindow.setWindowTitle(_translate("mywindow", "MainWindow"))
        self.label.setText(_translate("mywindow", "基于NumPy的图像分类卷积神经网络"))
        self.pushButton.setText(_translate("mywindow", "展示训练过程"))
        self.pushButton_2.setText(_translate("mywindow", "选择图片进行检测"))
        self.action112.setText(_translate("mywindow", "112"))
        self.action113.setText(_translate("mywindow", "113"))
        self.action114.setText(_translate("mywindow", "114"))
